#!/bin/sh

GIT_USERNAME=''
GIT_REPO_PATH=''
GIT_REPO_NAME=$1

cd $GIT_REPO_PATH
mkdir $GIT_REPO_NAME
cd $GIT_REPO_NAME

curl -u $GIT_USERNAME https://api.github.com/user/repos -d "{\"name\": \"$GIT_REPO_NAME\""

git init
git remote add origin https://github.com/$GIT_USERNAME/$GIT_REPO_NAME.git
touch README.md
git add .
git commit -m "initial commit"
git push -u origin master